const details = [
  {
    id: 26,
    name: "What's for dinner?",
    image: "images/recipy.png",
    link: "https://recipy-finder-api-871e7800ae87.herokuapp.com/",
    language: "JavaScript, React, API",
  },
  {
    id: 25,
    name: "Movie Finder",
    image: "images/movie.png",
    link: "https://movie-finder-api-ac1e36689a02.herokuapp.com/",
    language: "JavaScript, React, API",
  },
  {
    id: 24,
    name: "Books Finder",
    image: "images/books.png",
    link: "https://book-finder-api-ca8bf2c01233.herokuapp.com/",
    language: "JavaScript, React, API",
  },
  {
    id: 23,
    name: "🍎 Apple Catcher 🧺",
    image: "images/apple_catcher.png",
    link: "https://superlative-shortbread-44dd7e.netlify.app/",
    language: "JavaScript, CSS, Vite, Phaser",
  },
  {
    id: 22,
    name: "🃏 Flash Cards (API) 🤔",
    image: "images/flash.png",
    link: "https://bejewelled-unicorn-e13d98.netlify.app/",
    language: "JavaScript, CSS, React, API",
  },
  {
    id: 21,
    name: "👀 Minion 👀",
    image: "images/minion.png",
    link: "https://steady-tiramisu-8d8866.netlify.app/",
    language: "JavaScript, CSS",
  },
  {
    id: 20,
    name: "🔮Magic Ball 8🔮",
    image: "images/magic.png",
    link: "https://timely-fox-b010dc.netlify.app/",
    language: "DOM, JavaScript, CSS",
  },
  {
    id: 19,
    name: "🍪Pac-Man 👻",
    image: "images/pacman.png",
    link: "https://timely-cranachan-0d6ab6.netlify.app/",
    language: "DOM, JavaScript, CSS",
  },
  {
    id: 18,
    name: "🐍Snake Game",
    image: "images/snake.png",
    link: "https://fluffy-pudding-0f0eac.netlify.app/",
    language: "DOM, JavaScript, CSS",
  },
  {
    id: 17,
    name: "🔠Guess the Word!",
    image: "images/guesstheword.png",
    link: "https://tourmaline-cajeta-b0d8d8.netlify.app/",
    language: "DOM, JavaScript",
  },
  {
    id: 16,
    name: "🗺️Map your workouts",
    image: "images/map.png",
    link: "https://effervescent-travesseiro-b371e9.netlify.app/",
    language:
      "ObjectOrientedProgramming, JavaScript, Leaflet, API, Geolocation",
  },
  {
    id: 15,
    name: "💰Fictive Bank Site",
    image: "images/banking.jpg",
    link: "https://stirring-kashata-29068c.netlify.app/",
    language:
      "Advanced DOM manipulation, Slide element, Sticky Navigation, DOM events, IntersectionObserver, JavaScript, CSS",
  },
  {
    id: 14,
    name: "🕹️Games board",
    image: "images/games_board.PNG",
    link: "https://golden-gnome-e8d793.netlify.app/",
    language: "DOM manipulation, JavaScript, CSS",
  },
  {
    id: 13,
    name: "❌Tic-Tac-Toe",
    image: "images/tictactoe.png",
    link: "https://snazzy-speculoos-db3893.netlify.app/",
    language: "DOM manipulation, JavaScript, CSS",
  },
  {
    id: 12,
    name: "💵Fictive Virtual Personal Banking",
    image: "images/fictive_bank.png",
    link: "https://clinquant-cajeta-42eed6.netlify.app/",
    language: "DOM manipulation, JavaScript, CSS",
  },
  {
    id: 11,
    name: "🤯Memory Game",
    image: "images/memory1.png",
    link: "https://vermillion-tapioca-55e5ed.netlify.app/",
    language: "DOM manipulation, JavaScript, CSS",
  },
  {
    id: 10,
    name: "🧩Slide Puzzle",
    image: "images/sponge.png",
    link: "https://extraordinary-peony-cd46ff.netlify.app/",
    language: "DOM manipulation, JavaScript, CSS",
  },
  {
    id: 9,
    name: "🎲Dice Game",
    image: "images/pig-game.png",
    link: "https://ornate-halva-c5686c.netlify.app/",
    language: "DOM Class manipulation, JavaScript, CSS",
  },
  {
    id: 8,
    name: "🔢Guess the number!",
    image: "images/Guess_the_number.png",
    link: "https://soft-pika-ed6b48.netlify.app/",
    language: "DOM manipulation, JavaScript",
  },
  {
    id: 7,
    name: "🏋️‍♀️Javascript- exercises",
    image: "images/javascript.JPG",
    link: "https://astonishing-pasca-5a36aa.netlify.app/",
    language: "CSS, HTML, Express.js, Node.js",
  },
  {
    id: 6,
    name: "🪄Creative Project",
    image: "images/journey1.jpg",
    link: "https://www.victoriamoonteanu.com/",
    language: "CSS, HTML, Express.js, Node.js",
  },
  {
    id: 5,
    name: "Site Template",
    image: "images/extraterestrial.png",
    link: "https://vicmoon.github.io/CSS_SITE/",
    language: "CSS, HTML, Responsive Template",
  },
  {
    id: 4,
    name: "JavaScript Game",
    image: "images/game.png",
    link: "https://vicmoon.github.io/Javascript_Mainproject/",
    language: "CSS, HTML, JavaScript Game",
  },
  {
    id: 3,
    name: "React Dictionary",
    image: "images/Dictionary.JPG",
    link: "https://inspiring-tanuki-a897c7.netlify.app/",
    language: "CSS, API, HTML, JavaScript, React",
  },
  {
    id: 2,
    name: "Creative Project",
    image: "images/creatives.JPG",
    link: "https://playful-cuchufli-58a84f.netlify.app/",
    language: "CSS, HTML, Responsive Creative",
  },
  {
    id: 1,
    name: "World Clock App",
    image: "images/clock.JPG",
    link: "https://phenomenal-unicorn-f160f9.netlify.app/",
    language: "CSS, HTML, JavaScript, API, Responsive, moment.js",
  },
  {
    id: 0,
    name: "First Landing Page",
    image: "images/newlanding_page.JPG",
    link: "https://s3.amazonaws.com/shecodesio-production/challenge_submissions/files/001/286/709/original/basicaddon.html?1668786913",
    language: "CSS, HTML, Responsive",
  },
  {
    id: -1,
    name: "Weather App in React",
    image: "images/weather.JPG",
    link: "https://illustrious-beignet-228d77.netlify.app/",
    language: "React, CSS, HTML",
  },
  {
    id: -2,
    name: "JavaScript Weather App",
    image: "images/vanilajs.JPG",
    link: "https://vanillaweathersearch.netlify.app/",
    language: "JavaScript",
  },
  {
    id: -3,
    name: "Simple Landing Page",
    image: "images/landing.jpg",
    link: "https://s3.amazonaws.com/shecodesio-production/challenge_submissions/files/000/874/197/original/Finalproject.html?1653155333",
    language: "HTML, CSS",
  },
];

export default details;
